### ISSUE TITLE
Wrong result  for >=

### ISSUE THREAD

**Issue by McClean0815** [soukoku/ExpressionParser#3]
Hi,

thank you for this nice parser. I found a error when parsing >=

EvaluationContext context = new EvaluationContext();
Evaluator evaluator = new Evaluator(context);

ExpressionToken result = evaluator.Evaluate("1>=1");

result is "0"

Greetings,
Steffen

**Comment by soukoku** [comment]
Thanks for reporting this. Will be fixed in 2.4.1
