### ISSUE TITLE
Bug (fatal): unable to parse floating point number literals in cultures that use comma as decimal separator 

### ISSUE THREAD

**Issue by Rebel028** [soukoku/ExpressionParser#5]
`RawTokenizer.Tokenize()` uses default symbols array and counts comma as symbol, so numbers written like 36,6 are parsed wrong and cause the exception when `Evaluate()` is called.

On the other hand, `ExpressionToken.ToDecimal()` uses `CultureInfo.CurrentCulture` so if you try to pass the number with period as separator, it throws `System.FormatException`.

**Comment by soukoku** [comment]
I see. I may just use invariant culture for all things related to number parsing/formatting and only support dot as decimal point in expressions. 

I currently cannot support comma at all in numbers since I support functions and uses comma as the parameter separator. It'll be near impossible to tell if func(2,5) is one or two parameters if I try to allow it.

**Comment by Rebel028** [comment]
Thanks! In my use case InvariantCulture would be enough since there's no way for me to parse decimals now. 

InvariantCulture also means there will be predictable behaviour everywhere. Now I'm not sure of it, because if I containerize my app there may be a different locale inside a container and the code won't work as expected.

**Comment by soukoku** [comment]
I've put up 3.0.1 with invariant culture.

**Comment by Rebel028** [comment]
@soukoku thanks, but you've fixed only `ToDouble()` method, `ToDecimal()` still uses CurrentCulture: https://github.com/soukoku/ExpressionParser/blob/8677c771d8c9de9d0a2634098452d2f72648b075/src/ExpressionParser/ExpressionToken.cs#L209

**Comment by soukoku** [comment]
Can't believe I missed it. But in the end I had to use a real culture due to the way I've used it before (parse US currency) but should really behave the same as before.

**Comment by Rebel028** [comment]
Thanks a lot, it's working now.

Could you please reference in docs that user should use a period as decimal separator when working whith floating-point numbers?
